# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  secret_key_base: 159b58c8caf77a9e7bf289227b28b1d61956f1eca19530a72cd61636295cbe99757e4278399544a315ddd96c97b0443e65af8703fdb44ce72a5fc63c8454fe2c

test:
  secret_key_base: 94519f36b310c15f376f4e1e21b323e63c9f32fe1aa65471d42ac183c81a2ca916d0658ac994d4902dbb17d1d5cbf1db348cf1de09b253a4e6455bdf540223a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
